services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: small_business_booking_system

  mail:
    image: jcalonso/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

# раптом пише, що порт зайнятий - виконайте команду
# sudo kill $(lsof -t -i tcp:5432)