spring:
  application:
    name: small_business_booking_system


  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:small_business_booking_system}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:d159e3de-7f5b-4244-b989-0b34264c564a}
    password: ${GMAIL_PASSWORD:7b2d3eea-0143-4ab1-b1d4-5a4f213d4692}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:44af14bd-b032-40e1-9af8-0e5a0769fe2a}
  ttl-millis: 43200000 # 12 hours

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:3000}